rails-authorization/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "movies#index"

  resources :movies do
		resources :reviews, only: [:new, :show, :create]
	end
  resources :moviegoers, only: [:index, :new, :show, :create]

  get "/operations/top20", to: "operations#top20"
  get "/operations/bootstrap", to: "operations#bootstrap"
  
end

rails-authorization/app/models/movie.rb
class Movie < ApplicationRecord

    has_many :reviews, dependent: :destroy

    before_save :capitalize_title

    @@grandfathered_date = Date.parse('1 Nov 1968')

    def grandfathered?
        release_date && release_date < @@grandfathered_date
    end

    def self.all_ratings ; %w[G PG PG-13 R NC-17] ; end #  shortcut: array of strings

    def released_1930_or_later
        errors.add(:release_date, 'must be 1930 or later') if
                release_date && release_date < Date.parse('1 Jan 1930')
    end

    def capitalize_title
        self.title = self.title.split(/\s+/).map(&:downcase).
          map(&:capitalize).join(' ')
    end

    # model validation

	validates :title, :presence => true, uniqueness: { case_sensitive: false }
	validates :release_date, :presence => true
	validate :released_1930_or_later # uses custom validator below
	#validates :rating, :inclusion => {:in => Movie.all_ratings},
	#	:unless => :grandfathered?

    def avg_reviews
		sum = 0
		self.reviews.each do |review|
			sum = sum + review.potatoes
		end
		if self.reviews.count>0
			return sum/self.reviews.count
		else
			return "--"
		end
	end

end

rails-authorization/app/models/moviegoer.rb
class Moviegoer < ApplicationRecord
    has_many :reviews
	has_many :movies, :through => :reviews

    validates :name, uniqueness: true
end

rails-authorization/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie
	belongs_to :moviegoer

    validates :movie, uniqueness: { scope: :moviegoer,
        message: "one only review for a moviegoer" }
end

rails-authorization/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rails-authorization/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from CanCan::AccessDenied do |exception|
        redirect_to root_path, :alert => exception.message
    end
end

rails-authorization/app/controllers/moviegoers_controller.rb
class MoviegoersController < ApplicationController
	def index
		@moviegoers = Moviegoer.all
	end
	
	def show
		id = params[:id]
		@moviegoer = Moviegoer.find(id)
	end
	
	def new
		@moviegoer = Moviegoer.new
	end
	
	def create
		@moviegoer = Moviegoer.new(moviegoer_params)
		if @moviegoer.save
			redirect_to @moviegoer, notice: "Moviegoer was successfully created." 
		else
			render :new, status: :unprocessable_entity
		end
	end

	private

	def moviegoer_params
		params.require(:moviegoer).permit(:name)
	end
end

rails-authorization/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
    render('movie', movie: @movie) if request.xhr?
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)
    authorize! :create, @movie, :message => "BEWARE: you are not authorized to create new movies."

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    authorize! :destroy, @movie, :message => "BEWARE: you are not authorized to delete movies."
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :rating, :description, :release_date)
    end
end

rails-authorization/app/controllers/operations_controller.rb
class OperationsController < ApplicationController

    def top20
        if Tmdb.save_top20_popular_to_movies
            @message = 'Succeed'
        else
            @message = 'Failed'
        end
    end

    def bootstrap
    end
end

rails-authorization/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	
	def new
		id_movie = params[:movie_id]
		@movie = Movie.find(id_movie)
		@moviegoers = Moviegoer.all
		@review = Review.new
	end
	
	def create
		id_movie = params[:movie_id]
		@movie = Movie.find(id_movie)
		id_moviegoer = params[:review][:moviegoer_id]
		@moviegoer = Moviegoer.find(id_moviegoer)
		@moviegoers = Moviegoer.all
		@review = Review.new(review_params)
		@review.movie = @movie
		if @review.save
			redirect_to movie_path(@movie), notice: "A review has from #{@moviegoer.name} been successfully added to #{@movie.title}." 
		else
			render :new, status: :unprocessable_entity 
		end
	end

	def review_params
		params.require(:review).permit(:potatoes, :comments, :moviegoer_id)
	end
end

rails-authorization/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rottenpotatoes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      Logged in as <%= current_user.email%> [<%= link_to 'Logout', destroy_user_session_path, :method => :delete%>]
    <% end %>
    <%= yield %>
  </body>
</html>

rails-authorization/app/views/moviegoers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moviegoers</h1>

<ul>
  <%  @moviegoers.each do |moviegoer|  %>
    <li> <%= link_to moviegoer.name, moviegoer  %> </li>
  <% end %>
</ul>

<br>

<%= link_to 'Add Moviegoer', new_moviegoer_path %>

rails-authorization/app/views/moviegoers/new.html.erb
<h1>New Moviegoer</h1>

<%= form_with(model: @moviegoer) do |form| %>
    <% if @moviegoer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@moviegoer.errors.count, "error") %> prohibited this moviegoer from being saved:</h2>
  
        <ul>
          <% @moviegoer.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="actions">
      <%= form.submit "Add Moviegoer" %>
    </div>
<% end %>  

rails-authorization/app/views/moviegoers/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Details about <%= @moviegoer.name %></h2>

<h3> Movies reviewed so far </h3>
  <% if  @moviegoer.reviews.empty? %>
    <p> No reviews for this moviegoer... </p>
  <% else %>
    <ul>
    <%  @moviegoer.movies.each do |movie|  %>
      <li> <%= link_to movie.title, movie  %> </li>
    <% end %>
    </ul>
    
  <% end %>

rails-authorization/app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <% # changed with a selection %>
  <div class="field">
    <%= form.label :rating %><br>
    <%= form.select :rating, ['','G','PG','PG-13','R','NC-17'] %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <% # modified start years %>
  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date, start_year: 1930 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails-authorization/app/views/movies/index.html.erb
<h1>Movies</h1>
<div id ="movies">
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Release date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
    <!-- class adult to any table rows for movies rated other than G or PG -->
      <tr class="<%= ('adult' unless movie.rating =~ /^G|PG$/) %>">
        <td><%= movie.title %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.description %></td>
        <td><%= movie.release_date %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= if can? :destroy, movie then link_to 'Delete', movie, method: :delete, data: { confirm: 'Are you sure?' } end%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Movie', new_movie_path %> | <%= link_to 'Moviegoers List', moviegoers_path %>

<%= javascript_pack_tag 'movie_list_filter' %>

<%= javascript_pack_tag 'movie_popup' %>

rails-authorization/app/views/movies/movie.html.erb
<p> <%= @movie.description %> </p>

<%= link_to 'Edit Movie', edit_movie_path(@movie) %>
<%= link_to 'Close', '', :id => 'closeLink' %>

rails-authorization/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie.rating %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @movie.release_date %>
</p>

<h2> Reviews: </h2>
  <% if @movie.reviews.empty? %>
    <p>No reviews for this movie...</p>
  <% else %>
    <ul>
    <% @movie.reviews.each do |r| %>
      <li> <%= r.potatoes %> -  <%= Moviegoer.find(r.moviegoer_id).name %> </li>     
    <% end %>
    </ul>
  <% end %>

<%= link_to 'Add Review', new_movie_review_path(@movie) %> |
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

rails-authorization/app/views/operations/trigger.html.erb
<p> <%= @message %>

rails-authorization/app/views/reviews/new.html.erb
<h1>Add Review to <%= @movie.title %></h1>

<%= form_with model: [ @movie, @review ] do |form| %>

      <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
          <% @review.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :potatoes, 'Votes' %><br>
      <%= form.select :potatoes, [1,2,3,4,5] %>
    </div>

    <div class="field">
      <%= form.label :comments, 'Comment' %>
      <%= form.text_area:comments %>
    </div>

    <div class="field">
      <%= form.label :moviegoer_id, 'Moviegoer' %><br>
      <%= form.select :moviegoer_id, @moviegoers.collect { |moviegoer| [ moviegoer.name, moviegoer.id] } %>

    </div>

    <div class="actions">
      <%= form.submit "Add review" %>
    </div>
  <% end %>

rails-authorization/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

rails-authorization/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>